# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-14 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disk',
            name='server_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disk', to='cmdb.Hosts', verbose_name='所属服务器'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='server_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mem', to='cmdb.Hosts', verbose_name='所属服务器'),
        ),
        migrations.AlterField(
            model_name='nic',
            name='server_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nic', to='cmdb.Hosts', verbose_name='所属服务器'),
        ),
    ]
