# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-14 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20170614_2003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admininfo',
            options={'ordering': ['admin_type'], 'verbose_name_plural': '管理用户表'},
        ),
        migrations.AlterModelOptions(
            name='assetrecord',
            options={'ordering': ['asset_obj'], 'verbose_name_plural': '资产记录表'},
        ),
        migrations.AlterModelOptions(
            name='assets',
            options={'ordering': ['idc'], 'verbose_name_plural': '资产表'},
        ),
        migrations.AlterModelOptions(
            name='customtag',
            options={'ordering': ['name'], 'verbose_name_plural': '自定义标签'},
        ),
        migrations.AlterModelOptions(
            name='disk',
            options={'ordering': ['server_obj'], 'verbose_name_plural': '硬盘表'},
        ),
        migrations.AlterModelOptions(
            name='errorlog',
            options={'ordering': ['asset_obj'], 'verbose_name_plural': '错误日志表'},
        ),
        migrations.AlterModelOptions(
            name='hosts',
            options={'ordering': ['hostname'], 'verbose_name_plural': '服务器表'},
        ),
        migrations.AlterModelOptions(
            name='idc',
            options={'ordering': ['name'], 'verbose_name_plural': '机房表'},
        ),
        migrations.AlterModelOptions(
            name='memory',
            options={'ordering': ['server_obj'], 'verbose_name_plural': '内存表'},
        ),
        migrations.AlterModelOptions(
            name='networkdevice',
            options={'ordering': ['intranet_ip'], 'verbose_name_plural': '网络设备表'},
        ),
        migrations.AlterModelOptions(
            name='nic',
            options={'ordering': ['ipaddrs'], 'verbose_name_plural': '网卡表'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name'], 'verbose_name_plural': '项目表'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name'], 'verbose_name_plural': '安装服务表'},
        ),
        migrations.AlterModelOptions(
            name='usergroup',
            options={'ordering': ['name'], 'verbose_name_plural': '用户组表'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['sector'], 'verbose_name_plural': '用户表'},
        ),
    ]
