# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-14 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20170614_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='notes',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='备注'),
        ),
    ]
