# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-14 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_auto_20170614_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=128, verbose_name='项目备注'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='group_info',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='用户组描述'),
        ),
    ]
